### PR TITLE
[Bug 1340095] Escape colons in keys

### PR DESCRIPTION
**Pull request by MikkCZ**
This escapes colons in source files keys - should fix import of English strings into Pontoon. @vesper-mozilla @mathjazz r?

### CODE REVIEW

**Comment by mathjazz** [comment]
Escaping the colons doesn't seem to help. [Silme parser](https://github.com/mathjazz/silme/blob/master/lib/silme/format/properties/parser.py) treats both, `:` and `=` as key/value separators.

```
>>> from silme.format.properties import FormatParser
>>> structure = FormatParser.get_structure("key1\:key2 = value")
>>> structure.value("key1:key2")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/mathjazz/Desktop/pontoon/venv/lib/python2.7/site-packages/silme/core/structure.py", line 110, in value
    return self.entity(id).value
  File "/Users/mathjazz/Desktop/pontoon/venv/lib/python2.7/site-packages/silme/core/structure.py", line 167, in entity
    raise KeyError('No such entity')
KeyError: 'No such entity'
>>> structure.value("key1\\")
u'key2 = value'
```

**Comment by MikkCZ** [comment]
Hmm, that shouldn't be...

But e.g. pipe seems to work. @vesper-mozilla as you will be pasting the strings to Lithium manually, what will be more comfortable for you? I can replace all colons in the keys by pipes `|` (line `a:b = value` will become `a|b = value`) or just remove the colons completely (`a:b = value` will be `ab = value`). What will be more comfortable for you? I would prefer replacement by some unique character to avoid any collisions.

**Comment by vesper-mozilla** [comment]
I assume I will have to take all strings and bulk replace pipes (or any
other) placeholder with the colon before I paste the data into Lithium's
text console.

In this case, having an easily findable (and unique) character where the
colon should be for the purpose of batch text replace sounds best - so,
colons replaced by pipes make sense to me.

Thank you so much for your work on this!

**Comment by MikkCZ** [comment]
I have checked that pipes may be used in the string itself (in the value), but it shoudn't be hard to bulk replace in keys only.

**Comment by MikkCZ** [comment]
Let's close this without merging, as Lithium has not made it to the present.

**Pull request closed without merging**
